mobigen/datafairness-transform

- Openrefine/main/src/com/google/refine/commands/statistic/GetBasedStatisticCommand.java
- Openrefine/main/webapp/modules/core/MOD-INF/controller.js
- Openrefine/main/webapp/modules/core/scripts/dialogs/basic-statistics-dialog.js
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
- Openrefine/main/webapp/modules/core/styles/index/basic-statistics-dialog.css
기초통계치 chart 에 zoom기능 추가
버튼 제어 추가
빈도수 오류 수정
column 많은 프로젝트의 통계치 조회 오류 수정
그외 화면 오류 수정
> 기초 통계치 화면 오류 수정 및 개선

- Openrefine/main/src/com/google/refine/commands/statistic/GetBasedStatisticCommand.java
- Openrefine/main/webapp/modules/core/langs/translation-en.json
- Openrefine/main/webapp/modules/core/langs/translation-ko.json
- Openrefine/main/webapp/modules/core/scripts/dialogs/basic-statistics-dialog.js
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
- Openrefine/main/webapp/modules/core/styles/index/basic-statistics-dialog.css
- Openrefine/main/webapp/modules/core/styles/index/data-quality-ui.less
> 데이터 품질 평가 수정

- Openrefine/main/src/com/google/refine/commands/statistic/DataQualityUtils.java
- Openrefine/main/src/com/google/refine/commands/statistic/GetBasedStatisticCommand.java
- Openrefine/main/src/com/google/refine/commands/statistic/GetEvaluationIndexTestCommand.java
- Openrefine/main/webapp/modules/core/langs/translation-en.json
- Openrefine/main/webapp/modules/core/langs/translation-ko.json
- Openrefine/main/webapp/modules/core/scripts/dialogs/evaluation-index-dialog.html
- Openrefine/main/webapp/modules/core/scripts/dialogs/evaluation-index-dialog.js
- Openrefine/main/webapp/modules/core/styles/index/evaluation-index-dialog.css
- 품질평가 Dialog > grid column Sorting 동작 제대로 안됨 수정 (sorting > facet으로 변경처리)
- 품질평가 Dialog > Export porperties 입력 form 수정 (input > select)
> 데이터 품질 평가 화면 변경 및 오류 수정

- Openrefine/main/src/com/google/refine/statistic/AccuracyIndex.java
- Openrefine/main/src/com/google/refine/statistic/CompeletenessIndex.java
- Openrefine/main/src/com/google/refine/statistic/DataQualityIndex.java
- Openrefine/main/webapp/modules/core/scripts/dialogs/evaluation-index-dialog.html
- Openrefine/main/webapp/modules/core/scripts/dialogs/evaluation-index-dialog.js
- Openrefine/main/webapp/modules/core/scripts/dialogs/evaluation-index-properties.js
- Openrefine/main/webapp/modules/core/styles/index/data-quality-ui.less
- Openrefine/main/webapp/modules/core/styles/index/evaluation-index-dialog.css
> 품질평가 - 품질지표 frontend 수정

- vue-refine/src/views/afi/AFIMain.vue
- vue-refine/src/views/afi/comp/data-set-html.vue
- Card가 3페이지부터 시작하는 오류 수정
- 그 외 코드 수정
> [WEB] 공정성 Card 초기번호 오류 수정

- Openrefine/main/webapp/modules/core/langs/translation-en.json
- Openrefine/main/webapp/modules/core/langs/translation-ko.json
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
- 'DQ RULE' 버튼 클릭시 품질평가 WEB으로 연결
- 'FAIRNESS' 버튼 클릭시 공정성 WEB으로 연결
> [WEB] 데이터 품질 평가 ui에 공정성/RULE 설정 버튼 추가 (DQ-82)

- vue-refine/src/views/afi/cards/card-stepper.vue
> feat : 공정성 UI 부분 수정

- vue-refine/package-lock.json
- vue-refine/src/views/afi/AFIMain.vue
- vue-refine/src/views/afi/comp/data-set-chart.vue
- vue-refine/src/views/afi/comp/data-set-metrics.vue
- vue-refine/src/views/dqi/results/comp/number-stat.vue
- vue-refine/src/views/dqi/results/comp/string-stat.vue
- before/after metrics 값 grid로 표시
> feat : card3, 4 before/after metrics 값 표시 (DQ-81)

- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
> perf : DQI/AFI 웹페이지 Window.open 수정

- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
> fix : DQI/AFI 웹 연결 아이콘 제어

- vue-refine/src/App.vue
- vue-refine/src/common/modal/AppModal.vue
- vue-refine/src/common/scroll/ScrollTop.vue
- vue-refine/src/main.js
- vue-refine/src/router/routes.js
- vue-refine/src/views/default/Noty.vue
- vue-refine/src/views/dqi/rules/ViewRule.vue
- vue-refine/src/views/dqi/rules/comp/propertyBtns.vue
- RULE 스크롤 메뉴버튼 추가
- scrollTop 버튼 전역설정 및 DQI에서만 show
- Noty.vue 파일 생성 및 router 설정
> feat : 데이터품질 스크롤 버튼기능 추가

- Openrefine/main/webapp/modules/core/scripts/dialogs/basic-statistics-dialog.js
- Openrefine/main/webapp/modules/core/scripts/index/data-profiling-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
- Openrefine/main/webapp/modules/core/styles/index/data-quality-ui.less
- vue-refine/src/store/modules/afi.js
- 데이터 프로파일링 데이터 통계 표시 안되는 오류 수정
- 데이터 프로파일링 팝업페이지 chart width 조정
- 데이터 품질평가 오타 수정
> [WEB] Iris-refine 오류 수정 외

- Openrefine/main/webapp/modules/core/scripts/index/data-quality-ui.js
- vue-refine/src/common/scroll/ScrollTop.vue
- vue-refine/src/views/dqi/rules/comp/propertyBtns.vue
- window.open() 이벤트 수정 
- btn ui 수정
> [WEB] window.open 이벤트 수정 외

- Openrefine/main/webapp/modules/core/langs/translation-en.json
- Openrefine/main/webapp/modules/core/langs/translation-ko.json
- Openrefine/main/webapp/modules/core/scripts/index/data-fairness-ui.html
- Openrefine/main/webapp/modules/core/scripts/index/data-fairness-ui.js
- 데이터 품질평가 메뉴 내에 DQ-RULE/FAIRNESS 버튼을 분리하여 상위메뉴로 추가
> [WEB] 데이터 품질평가 메뉴 분리 (DQ-87) 

- vue-refine/src/views/dqi/results/comp/set-result-rules.vue
> perf : 지표설정 관련 문구 수정

- vue-refine/src/common/loader/Spinner.vue
> feat : 데이터품질 UI 수정

- vue-refine/src/assets/css/dev.scss
- vue-refine/src/store/modules/constants.js
- vue-refine/src/store/modules/results.js
- vue-refine/src/views/dqi/results/ViewResult.vue
- vue-refine/src/views/dqi/results/comp/ner-checkbox.vue
- vue-refine/src/views/dqi/results/comp/result-body.vue
- 자동 지표 측정 데이터 조회 후 RULE 기반 지표 측정 확인 할 수 있게 수정
- NER check box 추가
- 그 외 column locale 수정
> perf : 지표 측정 tab 제어 외 (DQ-92)

- vue-refine/src/views/afi/comp/data-set-array.vue
> fix : 공정성 UI 에러 수정

- Openrefine/main/webapp/modules/core/scripts/dialogs/basic-statistics-dialog.js
- 프로파일링 > 데이터 통계 > '보기' 부분 코드 주석처리 (미구현)
> fix : 프로파일링 디테일 개발 미구현인 부분 주석처리

- vue-refine/package-lock.json
- vue-refine/package.json
- vue-refine/src/common/chart/index.js
- vue-refine/src/main.js
- vue-refine/src/store/modules/afi.js
- vue-refine/src/views/afi/cards/compare.vue
- vue-refine/src/views/afi/cards/set-mitigate.vue
- vue-refine/src/views/afi/comp/data-set-chart.vue
- vue-refine/src/views/afi/comp/data-set-metrics.vue
- vue-refine/vue.config.js
- 공정성 Step3, Step4 Grid에서  Metrics 차트로 변경
- 데이터 조회 오류 수정
> [WEB] 공정성 결과값 Chart화 (DQ-97)

- vue-refine/src/views/afi/comp/data-set-chart.vue
- vue-refine/src/views/afi/comp/data-set-metrics.vue
- 공정성 Step3, Step4 Metrics 부분 button 추가
- 버튼으로 BAR chart / LINE chart 표시하도록 제어 추가
> [WEB] 공정성 결과값 LINE Chart 추가 (DQ-100)

- vue-refine/src/views/afi/comp/data-set-chart.vue
- popup 창으로 표시될때, width가 잘못 계산되어 화면을 벗어나는 현상 수정
> feat : 공정성 Metrics chart width 수정

- vue-refine/src/apis/results.js
- vue-refine/src/router/routes.js
- vue-refine/src/store/modules/results.js
- vue-refine/src/views/dqi/results/ViewCorrection.vue
- vue-refine/src/views/dqi/results/ViewResult.vue
- 품질평가 페이지에서 데이터 조회 클릭시에만 보정 버튼 show
- column select box, setting select box 기능 구현
- 보정 실행 버튼 클릭시 api 호출
- 실행 시 받은 table_name 값으로 column_dqi 값 조회
> feat : 품질평가 보정페이지 구현

- vue-refine/src/views/afi/comp/data-set-metrics.vue
- vue-refine/src/views/dqi/results/comp/dqi-chart-bar.vue
- vue-refine/src/views/dqi/results/comp/dqi-chart-gauge.vue
- vue-refine/src/views/dqi/results/comp/dqi-grid.vue
- vue-refine/src/views/dqi/results/comp/percentage-box.vue
- vue-refine/src/views/dqi/results/comp/result-body.vue
- vue-refine/src/views/dqi/results/comp/result-column-simple-table.vue
- 품질평가 지표측정 결과창 화면에서 전체통계 Bar 차트 추가
- 컬럼별 통계 Table에서 데이터 지표값을 Bar 차트로 변경
> [WEB] 품질평가 지표측정 결과값 Chart추가 외 (DQ-103)

- vue-refine/src/views/dqi/results/comp/percentage-box.vue
> fix : 컬럼별 통계 bar div chart width 오류 수정

- vue-refine/src/views/dqi/results/ViewCorrection.vue
> fix : prettier 적용

- vue-refine/src/views/dqi/results/ViewCorrection.vue
- 보정페이지 (보정된 ROW 수 / 전체 ROW수) text 출력
> feat : 보정페이지 row 수 출력

- vue-refine/src/views/dqi/results/ViewResult.vue
> fix : tab 처리방식 수정

- vue-refine/src/views/dqi/results/ViewCorrection.vue
- vue-refine/src/views/dqi/results/comp/correction-chart-doughnut.vue
> fix : 보정페이지 에러 수정

- vue-refine/src/mixins/afiMixin.js
- vue-refine/src/store/modules/afi.js
- 공정성 평가 지표 설정시, 기본값으로 표시해주고 있던 부분 삭제처리.
> perf : 공정성 평가 기본값 삭제

- vue-refine/src/views/dqi/results/ViewCorrection.vue
- RULE 기반 데이터 조회시 보정페이지 mode에rule이 아닌 auto로 set
> fix : 보정 페이지 에러 수정
